// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Router from "../Router/Router.bs.js";

function App(Props) {
  return React.createElement("div", {
              className: "App"
            }, React.createElement(Router.make, {}));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
