// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function App(Props) {
  return React.createElement("div", {
              className: "App"
            });
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
